[2023/02/09]-AlbumSharing기능구현/chopmozzi
App-in-App-le/NostelgiAlbum pull request #23
Opened 2023-02-08 17:14 UTC by chopmozzi

## 작성 내용
- UIActivityViewController를 활용한 Album Sharing기능 구현
- share button을 클릭 시 share sheet가 열리면서 share button을 누른 위치의 Album의 공유를 할 수 있게 함
- Album은 albumdirectory가  zip -> nost의 확장자를 거쳐 공유가 되며 receiver측에서는 nost -> zip의 순서를 거쳐 unzip을 하여 album이 receiver의 album 목록에 들어갈 수 있도록 함.
- nost파일을 열 때 share sheet목록에서 NostelgiAlbum을 선택하면 app이 열리면서 공유 받을 수 있게 됨 -> `SceneDelegate`에서 `url.scheme`를 활용함
- nost라는 custom extension을 활용함에 따라 `Info.plist`수정 및 `xcodeproj`수정

## 특이사항
- Mac에서 xcode simulator를 이용해 테스트 할 시 save to file을 통해 나의 iPhone폴더에 저장한 후 이용 가능
- iPhone device에 연결하여 테스트 시 카카오톡으로 파일 전송 후 파일을 다운로드 받을 시 공유 기능 테스트 가능
- 현재 자기 device로 밖에 테스트를 못하기 때문에 공유시 사용했던 album후 공유 기능 테스트를 하기 바람(directory의 이름이 똑같을 시의 예외 처리를 하지 않음)
- `SceneDelegate`에서 `rootViewController`를 활용함에 따라 viewController의 초기화에서 문제 발생(Storyboard활용에 따른)
- 주석 필요
- 코드 리팩토링 필요(hierarchy에서 용도가 맞지 않거나 불필요한 라이브러리를 import하게 되는 부분이 있음)
- 공유를 통해 받은 Album을 modifying Album기능으로 동작시킬 필요가 있음(현재 Album이름은 고정 coverImageColor는 red로 통일)

2023-02-10 11:07 UTC, jeonmmingu requested changes
Please Check my reviews 🔥

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +    _ = FileManager.default
### [ Question ]
" `_ = FileManager.default `" 이건 무슨 의미죠??

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +    for i in 1...albumInfo.first!.numberOfPictures {
### [Code Review]

- albumInfo에서 numberOfPictures를 가져올 필요 없이

```
for album in albumData {
      arrImageText.append("\(album.ImageText)")
      arrImageName.append("\( album.ImageName)")
}
```
이렇게 쓸 수 있을 것 같습니다!

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +func addAlbumInfo(coverData: String) {
### [Code Review]

- 함수 명으로 `addAlbumInfo` 보단  `extractAlbumInfo` 혹은 `loadAlbumInfo` 가 적절할 것 같습니다.

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/AppDelegate.swift
> +    var window: UIWindow?
### [Question]

- `var window: UIWindow?` 는 왜 추가하셨나요?

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/SceneDelegate.swift
> +    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
### [Question]

- 이 부분도 설명해주시면 감사하겠습니다. 🐶

2023-02-10 11:07 UTC, jeonmmingu commented on NostelgiAlbum/Info.plist
> -	<key>NSCameraUsageDescription</key>
### [Question]

- `Camera`랑 `Photo`의 `Usage Description`은 `AlbumEditViewController`에서 사진 불러올 때 `Picker` 때문에 표기해줘야 할 것 같은데 `Delete` 해도 잘 동작하나요?

2023-02-12 17:50 UTC, chopmozzi commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +    _ = FileManager.default
오타입니다. 삭제 완료

2023-02-12 17:50 UTC, chopmozzi commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +    for i in 1...albumInfo.first!.numberOfPictures {
Good idea. 수정했습니다.

2023-02-12 17:55 UTC, chopmozzi commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +func addAlbumInfo(coverData: String) {
albumInfo를 txt file로 따로 추출하는 의미가 더 적합한거 같아 exportAlbumInfo로 지정했습니다.
이에 대응하는 함수인 addShareAlbum의 이름도 importAlbumInfo로 수정했습니다.

2023-02-12 17:57 UTC, chopmozzi commented on NostelgiAlbum/SceneDelegate.swift
> +    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
SceneDelegate는 화면에 어떤 scene을 띄울지 관리하는데, 이때 특정 URL을 눌렀을 때의 동작을 설정하는 scene function입니다(URL Contexts를 인자로 받는 scene function입니다).
주석 추가 하였으니 질문 바랍니다.

2023-02-12 17:58 UTC, chopmozzi commented on NostelgiAlbum/Info.plist
> -	<key>NSCameraUsageDescription</key>
이건 제가 Info.plist에 파일 공유 관련 권한 설정하다가 실수로 추가하고 다시 뺀 항목 같습니다. Camera 및 Photo의 동작 확인했습니다.

2023-02-12 17:59 UTC, chopmozzi commented
code Refactoring 및 이전에 오류가 있었던 search function과 이미지 이름이 아니라 앨범 타이틀이 들어가던 오류 수정했으니 추가 확인바랍니다.

2023-02-12 18:00 UTC, chopmozzi commented
Album gesture는 구조 자체를 좀 건드려야 할 거 같아서 해당 부분은 추후에 하겠습니다.

2023-02-12 18:02 UTC, chopmozzi commented on NostelgiAlbum/AppDelegate.swift
> +    var window: UIWindow?
삭제했습니다. SceneDelegate를 쓰는 지금으로선 필요 없는 파트입니다.
추후 iOS 13이전의 버전을 컨트롤하게 된다면 다시 추가하겠습니다.

2023-02-13 02:54 UTC, jeonmmingu commented on NostelgiAlbum/SceneDelegate.swift
> +    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
확인했습니다 ~~ 감사합니다 :-)

2023-02-13 02:56 UTC, jeonmmingu commented on NostelgiAlbum/ImageFunc/ImageFunc.swift
> +func addAlbumInfo(coverData: String) {
확인했습니다 :0

2023-02-13 03:03 UTC, jeonmmingu approved these changes

2023-02-13 03:04 UTC, jeonmmingu commented
LGTM🔥 고생하셨습니다 :)

2023-02-13 03:05 UTC, jeonmmingu commented
LGTM🔥 고생하셨습니다 :)

2023-02-13 03:06 UTC, jeonmmingu commented
LGTM🔥 고생하셨습니다 :)

2023-02-13 03:06 UTC, merged